// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_c7cd2602767f0a10, []int{0}
}
func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (dst *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(dst, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

type GetTodosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodosRequest) Reset()         { *m = GetTodosRequest{} }
func (m *GetTodosRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodosRequest) ProtoMessage()    {}
func (*GetTodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_c7cd2602767f0a10, []int{1}
}
func (m *GetTodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosRequest.Unmarshal(m, b)
}
func (m *GetTodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosRequest.Marshal(b, m, deterministic)
}
func (dst *GetTodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosRequest.Merge(dst, src)
}
func (m *GetTodosRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodosRequest.Size(m)
}
func (m *GetTodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosRequest proto.InternalMessageInfo

type GetTodosResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodosResponse) Reset()         { *m = GetTodosResponse{} }
func (m *GetTodosResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodosResponse) ProtoMessage()    {}
func (*GetTodosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_c7cd2602767f0a10, []int{2}
}
func (m *GetTodosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosResponse.Unmarshal(m, b)
}
func (m *GetTodosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosResponse.Marshal(b, m, deterministic)
}
func (dst *GetTodosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosResponse.Merge(dst, src)
}
func (m *GetTodosResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodosResponse.Size(m)
}
func (m *GetTodosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosResponse proto.InternalMessageInfo

func (m *GetTodosResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func init() {
	proto.RegisterType((*Todo)(nil), "Todo")
	proto.RegisterType((*GetTodosRequest)(nil), "GetTodosRequest")
	proto.RegisterType((*GetTodosResponse)(nil), "GetTodosResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReadOnlyTodoClient is the client API for ReadOnlyTodo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReadOnlyTodoClient interface {
	GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error)
}

type readOnlyTodoClient struct {
	cc *grpc.ClientConn
}

func NewReadOnlyTodoClient(cc *grpc.ClientConn) ReadOnlyTodoClient {
	return &readOnlyTodoClient{cc}
}

func (c *readOnlyTodoClient) GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error) {
	out := new(GetTodosResponse)
	err := c.cc.Invoke(ctx, "/ReadOnlyTodo/GetTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadOnlyTodoServer is the server API for ReadOnlyTodo service.
type ReadOnlyTodoServer interface {
	GetTodos(context.Context, *GetTodosRequest) (*GetTodosResponse, error)
}

func RegisterReadOnlyTodoServer(s *grpc.Server, srv ReadOnlyTodoServer) {
	s.RegisterService(&_ReadOnlyTodo_serviceDesc, srv)
}

func _ReadOnlyTodo_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadOnlyTodoServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReadOnlyTodo/GetTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadOnlyTodoServer).GetTodos(ctx, req.(*GetTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReadOnlyTodo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ReadOnlyTodo",
	HandlerType: (*ReadOnlyTodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodos",
			Handler:    _ReadOnlyTodo_GetTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_todo_c7cd2602767f0a10) }

var fileDescriptor_todo_c7cd2602767f0a10 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0xd4, 0x48, 0x9d, 0x8a, 0xb6, 0x8b, 0x87, 0x10, 0x0f, 0x86, 0x9c, 0xf6, 0xb4,
	0xc1, 0x08, 0xde, 0x3d, 0x79, 0x14, 0x96, 0xfe, 0x81, 0x94, 0x19, 0xcb, 0xc2, 0x36, 0x13, 0xdd,
	0xe9, 0xc1, 0x7f, 0x2f, 0xc9, 0x12, 0x0b, 0x39, 0xce, 0x9b, 0xc7, 0xfb, 0x3e, 0x00, 0x61, 0x64,
	0x3b, 0xfc, 0xb0, 0x70, 0xf9, 0x7c, 0x64, 0x3e, 0x06, 0x6a, 0xa6, 0xeb, 0x70, 0xfe, 0x6a, 0xc4,
	0x9f, 0x28, 0x4a, 0x77, 0x1a, 0x52, 0xa1, 0x46, 0xb8, 0xde, 0x33, 0xb2, 0xbe, 0x87, 0xcc, 0x63,
	0xa1, 0x2a, 0x65, 0x72, 0x97, 0x79, 0xd4, 0x8f, 0x90, 0x8b, 0x97, 0x40, 0x45, 0x56, 0x29, 0x73,
	0xeb, 0xd2, 0xa1, 0xdf, 0x60, 0x8d, 0xd4, 0x61, 0xf0, 0x3d, 0x15, 0xab, 0x4a, 0x99, 0x4d, 0x5b,
	0xda, 0x44, 0xb0, 0x33, 0xc1, 0xee, 0x67, 0x82, 0xfb, 0xef, 0xd6, 0x3b, 0x78, 0xf8, 0x20, 0x19,
	0x41, 0xd1, 0xd1, 0xf7, 0x99, 0xa2, 0xd4, 0x0d, 0x6c, 0x2f, 0x51, 0x1c, 0xb8, 0x8f, 0xa4, 0x9f,
	0x20, 0x1f, 0xdd, 0x63, 0xa1, 0xaa, 0x95, 0xd9, 0xb4, 0xb9, 0x1d, 0xdf, 0x2e, 0x65, 0xed, 0x3b,
	0xdc, 0x39, 0xea, 0xf0, 0xb3, 0x0f, 0xbf, 0x93, 0xf1, 0x0b, 0xac, 0xe7, 0x01, 0xbd, 0xb5, 0x8b,
	0xf9, 0x72, 0x67, 0x97, 0xeb, 0xf5, 0xd5, 0xe1, 0x66, 0x92, 0x7c, 0xfd, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x00, 0xfb, 0xc9, 0xf2, 0x22, 0x01, 0x00, 0x00,
}
